language: java
jdk:
  - oraclejdk8
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Djavax.xml.accessExternalSchema=all -B -V
script:
  - mvn test -B
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - '$HOME/.m2/repository'
